services:
  development_db:
    container_name: postgres-logistic-tech-dev
    image: postgres:16.3
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  test_db:
    container_name: postgres-logistic-tech-test
    image: postgres:16.3
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST_TEST}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_TEST}
      POSTGRES_USER: ${POSTGRES_USER_TEST}
      POSTGRES_DB: ${POSTGRES_DB_TEST}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT_TEST}:5432"

volumes:
  pgdata:
